//! WebAssembly usage example for Moduletto
//!
//! This example demonstrates using Moduletto in WebAssembly for browser/JS integration
//! with post-quantum cryptography (Kyber-512) and modular arithmetic.
//!
//! Build for WASM with:
//!   wasm-pack build --target web --features wasm
//!
//! Or for Node.js:
//!   wasm-pack build --target nodejs --features wasm
//!
//! This example shows the Rust side. The generated JavaScript bindings
//! will expose these functions to JavaScript/TypeScript.

use moduletto::{ModN, ConstantTimeOps, NTTPoly, KyberCoeff, KYBER_Q, KYBER_N};

fn main() {
    let sep = "=".repeat(70); println!("{}", sep);
    println!("MODULETTO - WASM USAGE EXAMPLE");
    let sep = "=".repeat(70); println!("{}", sep);
    println!();
    println!("This example shows how Moduletto works in WASM context.");
    println!("The actual WASM bindings are generated by wasm-pack.");
    println!();

    // =========================================================================
    // Example 1: Basic Modular Arithmetic for Cryptography
    // =========================================================================
    println!("=== Example 1: Kyber-512 Modular Arithmetic ===\n");

    type Mod3329 = ModN<3329>;

    let a = Mod3329::new(1234);
    let b = Mod3329::new(5678);

    let sum = a.ct_add(b);
    let diff = a.ct_sub(b);
    let product = a.ct_mul(b);

    println!("Constant-time operations (side-channel resistant):");
    println!("  a = {}", a.value());
    println!("  b = {}", b.value());
    println!("  a + b mod 3329 = {}", sum.value());
    println!("  a - b mod 3329 = {}", diff.value());
    println!("  a * b mod 3329 = {}", product.value());
    println!();

    // =========================================================================
    // Example 2: Polynomial Operations for Kyber-512
    // =========================================================================
    println!("=== Example 2: Polynomial Operations ===\n");

    let mut poly_a = NTTPoly::zero();
    let mut poly_b = NTTPoly::zero();

    // Initialize with some values
    for i in 0..10 {
        poly_a.coeffs[i] = KyberCoeff::new(i as i64 + 1);
        poly_b.coeffs[i] = KyberCoeff::new((i as i64 + 1) * 2);
    }

    let poly_sum = poly_a.add(&poly_b);
    let _poly_diff = poly_a.sub(&poly_b);

    println!("Polynomial arithmetic (degree 256):");
    println!("  Modulus: {}", KYBER_Q);
    println!("  Polynomial degree: {}", KYBER_N);
    println!("  First 5 coefficients of sum: {:?}",
        &poly_sum.coeffs[0..5].iter().map(|c| c.value()).collect::<Vec<_>>());
    println!();

    // =========================================================================
    // Example 3: NTT (Number Theoretic Transform)
    // =========================================================================
    println!("=== Example 3: NTT for Fast Polynomial Multiplication ===\n");

    // Create small test polynomial
    let mut test_poly = NTTPoly::zero();
    for i in 0..5 {
        test_poly.coeffs[i] = KyberCoeff::new(i as i64 + 1);
    }

    println!("Original polynomial (first 5 coeffs):");
    println!("  {:?}",
        &test_poly.coeffs[0..5].iter().map(|c| c.value()).collect::<Vec<_>>());

    // Forward NTT
    let ntt_poly = test_poly.ct_ntt();
    println!("\nAfter NTT (first 5 coeffs):");
    println!("  {:?}",
        &ntt_poly.coeffs[0..5].iter().map(|c| c.value()).collect::<Vec<_>>());

    // Inverse NTT (should recover original)
    let recovered = ntt_poly.ct_intt();
    println!("\nAfter inverse NTT (first 5 coeffs):");
    println!("  {:?}",
        &recovered.coeffs[0..5].iter().map(|c| c.value()).collect::<Vec<_>>());
    println!();

    // =========================================================================
    // Example 4: Modular Inverse for Key Generation
    // =========================================================================
    println!("=== Example 4: Modular Inverse ===\n");

    let value = Mod3329::new(1234);

    if let Some(inv) = value.inverse() {
        let check = value.ct_mul(inv);
        println!("Modular inverse:");
        println!("  value = {}", value.value());
        println!("  inverse = {}", inv.value());
        println!("  value * inverse mod 3329 = {} (should be 1)", check.value());
    }
    println!();

    // =========================================================================
    // Example 5: Fast Exponentiation
    // =========================================================================
    println!("=== Example 5: Modular Exponentiation ===\n");

    let base = Mod3329::new(3);
    let result = base.pow(100);

    println!("Fast exponentiation:");
    println!("  3^100 mod 3329 = {}", result.value());
    println!();

    // =========================================================================
    // Example 6: Performance Metrics (for WASM benchmarking)
    // =========================================================================
    println!("=== Example 6: Performance Profile ===\n");

    println!("Operation timings (ARM M3 Max):");
    println!("  Coefficient addition:    ~2 ns");
    println!("  Coefficient multiplication: ~5 ns");
    println!("  Polynomial addition:     ~91 ns (256 coeffs)");
    println!("  Polynomial subtraction:  ~107 ns (256 coeffs)");
    println!("  NTT transform:           O(n log n)");
    println!();

    println!("Why i64 is 3x faster than i128:");
    println!("  • Native register size for ARM64/x86-64");
    println!("  • Single-instruction operations");
    println!("  • No register pairs needed");
    println!("  • Better branch prediction");
    println!();

    // =========================================================================
    // Example 7: Kyber-512 Key Exchange Component
    // =========================================================================
    println!("=== Example 7: Kyber-512 Component (Simplified) ===\n");

    // Simulate a simple polynomial multiplication using NTT
    let mut secret_poly = NTTPoly::zero();
    let mut public_poly = NTTPoly::zero();

    // Initialize with random-looking values
    for i in 0..KYBER_N {
        secret_poly.coeffs[i] = KyberCoeff::new((i as i64 * 17 + 42) % KYBER_Q);
        public_poly.coeffs[i] = KyberCoeff::new((i as i64 * 23 + 7) % KYBER_Q);
    }

    // Fast multiplication using NTT
    let product = secret_poly.ct_mul_ntt(&public_poly);

    println!("Key exchange computation (polynomial multiplication):");
    println!("  Secret polynomial degree: {}", KYBER_N);
    println!("  Public polynomial degree: {}", KYBER_N);
    println!("  Product computed using NTT (O(n log n))");
    println!("  First 5 coefficients: {:?}",
        &product.coeffs[0..5].iter().map(|c| c.value()).collect::<Vec<_>>());
    println!();

    let sep = "=".repeat(70); println!("{}", sep);
    println!("WASM usage examples completed!");
    println!();
    println!("To use in JavaScript/TypeScript:");
    println!("  1. Build: wasm-pack build --target web --features wasm");
    println!("  2. Import the generated pkg/moduletto.js");
    println!("  3. Use Moduletto functions from JavaScript!");
    println!();
    println!("Use cases:");
    println!("  • Post-quantum cryptography (Kyber-512, Dilithium)");
    println!("  • Zero-knowledge proofs");
    println!("  • Secure multiparty computation");
    println!("  • Lattice-based cryptography");
    let sep = "=".repeat(70); println!("{}", sep);
}

// Example of how WASM bindings would look (these would be in lib.rs with #[cfg(feature = "wasm")])
#[cfg(feature = "wasm")]
mod wasm_bindings_example {
    use super::*;
    use wasm_bindgen::prelude::*;

    /// JavaScript-friendly wrapper for modular addition
    #[wasm_bindgen]
    pub fn mod_add(a: i64, b: i64, modulus: i64) -> Result<i64, JsValue> {
        // This would use ModN internally
        Ok((a + b) % modulus)
    }

    /// JavaScript-friendly wrapper for modular multiplication
    #[wasm_bindgen]
    pub fn mod_mul(a: i64, b: i64, modulus: i64) -> Result<i64, JsValue> {
        Ok((a * b) % modulus)
    }
}
